import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/auth";
import { Toaster } from "@/app/base_ui/ui/sonner";
import { ThemeProvider } from "./context/theme";
import { UserDetailsProvider } from "./context/user";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={inter.className}
      >
        <UserDetailsProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <AuthProvider>
              <Toaster />
              {children}
            </AuthProvider>
          </ThemeProvider>
        </UserDetailsProvider>


      </body>
    </html>
  );
}
