export enum ErrorCode {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  CONNECTION_API_ERROR = "CONNECTION_API_ERROR",
  ACCOUNT_ALREADY_EXIST = "ACCOUNT_ALREADY_EXIST",
  UNOTHORIZED_ACCOUNT = "UNOTHORIZED_ACCOUNT",
  LOGIN_REQUIRED = "LOGIN_REQUIRED"
}
